# Secrets.toml is a .env for services deployed to shuttle.rs
DOTENV_OK      ="1"
RUST_LOG       ="DEBUG"
SHUTTLE_API_KEY="3Ff1tmbCptofqbZU"
DB_PASSWORD    ="postgres"
DB_PORT        ="5432"             # default port for postgres
