# Secrets.toml is a .env for services deployed to shuttle.rs
DOTENV_OK      ="1"
RUST_LOG       ="DEBUG"
DB_PASSWORD    ="postgres"
DB_PORT        ="5432"             # default port for postgres
SHUTTLE_API_KEY=""
ANALYTICS_API_KEY ="" # api analytics key