# Auto-update github dependencies. 
# last updated 2024-03-04

# demo: https://github.com/dependabot/demo/blob/main/.github/dependabot.yml
# docs:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# docs - cargo in package-ecosystem:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
---
version: 2
updates:
  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions" 
    directory: "/"
    schedule:
      interval: "weekly"
  # Check for updates to Cargo.toml dependencies every week
  - package-ecosystem: cargo
    directory: "/"
    schedule: 
      interval: "weekly"

# other examples:
  # - package-ecosystem: npm
  #   directory: "/javascript"
  #   schedule:
  #     interval: "weekly"
  # - package-ecosystem: bundler
  #   directory: "/ruby"
  #   schedule:
  #     interval: "weekly"
